[package]
name = "untitled"
version = "0.1.0"
authors = ["Kyle Cooke <kyle@playerdata.co.uk>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
assert-json-diff = "2.0.1"